### ISSUE TITLE
For a given gray image with high contrast, how to process it to pull it into training data distribution for better result

### ISSUE THREAD

**Issue by Sutongtong233** [piddnad/DDColor#40]
Hi, I find that, for some gray image with very high contrast, processing it by decreasing contrast can lead to better results. Perhaps the reason is that it aligns more closely with the distribution of the training data. 
I wonder if there is any general algorithm or code that can process any given grayscale image, taking into account statistical properties such as color temperature and hue? Thanks a lot!

**Comment by piddnad** [comment]
Hi @Sutongtong233 ! As far as I know, since grayscale images represent light intensity, there is no color information. As a result, they do not have properties such as hue or color temperature.

However, you can analyze and manipulate grayscale images based on intensity values (brightness) and their histograms (distribution of intensity values). For example, you can use OpenCV for histogram normalization, histogram equalization to enhance image contrast and so on. The corresponding can be found simply by searching online.

**Comment by Sutongtong233** [comment]
thanks :)
