### ISSUE TITLE
color embeddings are initialized to zero

### ISSUE THREAD

**Issue by yingdundun** [piddnad/DDColor#42]
Mentioned in the paper：”These color embeddings are initialized to zero during the training phase and used as color queries in the first CDB” , but  I can't find the code in the code that initializes to zero  in question. Is the initialization to zero mentioned in the paper really zero? Looking forward to your answers.

**Comment by piddnad** [comment]
Hi @yingdundun , that's a good question! 

After checking the [code](https://github.com/piddnad/DDColor/blob/8d3f8f28bbb1783e96cca2c91bee3cef486c09e0/basicsr/archs/ddcolor_arch.py#L262), I found that the color query is using the default initialization of `nn.Embedding`, that is to say, they are actually initialized from a normal distribution rather than zeros.

**Comment by yingdundun** [comment]
> 嗨，这是个好问题！
> 
> 检查[代码](https://github.com/piddnad/DDColor/blob/8d3f8f28bbb1783e96cca2c91bee3cef486c09e0/basicsr/archs/ddcolor_arch.py#L262)后，我发现颜色查询使用的是默认的初始化，也就是说，它们实际上是从正态分布而不是零初始化而来的。`nn.Embedding`

Thanks for your reply.
