### ISSUE TITLE
Help understanding the pre and post processing code

### ISSUE THREAD

**Issue by shubhamgupto** [piddnad/DDColor#52]
Hello @piddnad and authors,

Thank you for open sourcing DDColor! I am interested in running this model on edge devices and im trying to reduce as many operation overheads as possible.

I noticed the input to the model is of channel size 3 even though we are feeding it grayscale images and the output channel is 2. Could you help me understand the pre and post processing done ?

preprocessing
```
input_size = 512
batch_size = 1
height, width = img.shape[:2]
# print(self.width, self.height)
# if self.width * self.height < 100000:
#     self.input_size = 256

img = (img / 255.0).astype(np.float32)
orig_l = cv2.cvtColor(img, cv2.COLOR_BGR2Lab)[:, :, :1]  # (h, w, 1)

# resize rgb image -> lab -> get grey -> rgb
img_resize = cv2.resize(img, (input_size, input_size))
img_l = cv2.cvtColor(img_resize, cv2.COLOR_BGR2Lab)[:, :, :1]
img_gray_lab = np.concatenate((img_l, np.zeros_like(img_l), np.zeros_like(img_l)), axis=-1)
print(img_gray_lab.shape)
img_gray_rgb = cv2.cvtColor(img_gray_lab, cv2.COLOR_LAB2RGB)

img_gray_rgb = img_gray_rgb.transpose((2, 0, 1)).astype(np.float32)
img_gray_rgb = np.expand_dims(img_gray_rgb, axis=0)

# Psuedo-batch the input images
img_gray_rgb = np.concatenate([img_gray_rgb for _ in range(batch_size)], axis=0)
```

postprocessing
```
output_ab = torch.from_numpy(ort_session.run(None, inputs)[0])
output_ab_resize = F.interpolate(output_ab, size=(height, width))[0].float().numpy().transpose(1, 2, 0)
output_lab = np.concatenate((orig_l, output_ab_resize), axis=-1)
output_rgb = cv2.cvtColor(output_lab, cv2.COLOR_LAB2RGB)

output_img = (output_rgb * 255.0).round().astype(np.uint8)  
```

Thank you again!

**Comment by piddnad** [comment]
Hi @shubhamgupto , thanks for your interest in our work!

The core idea of preprocessing is to **construct a three-channel RGB grayscale image** (since the model was trained on RGB format inputs). Therefore, we resize the given input image, extract the L channel, create a three-channel grayscale image (where only the L channel is meaningful, and the A and B channels are filled with 0), and then convert it back to RGB format.

The core idea of postprocessing is to **concatenate the A and B channels output by the model with the input L channel** (because when colorizing, we typically do not want to alter the original image's L channel, i.e. the texture). Thus, we resize the output A and B channels, concatenate them with the input L channel, and convert the result to RGB format for saving.

Hope these explanations help you understand the code implementation.

**Comment by shubhamgupto** [comment]
Hey @piddnad Thank you for the explanation! Any chance there's a way to build an even smaller DDColor model than `ddcolor-paper-tiny.pth` ? 

The pretrained weights released use the `MultiScaleColorDecoder`, are there any weights for the `SingleColorDecoder`? with ConvNext-tiny encoder ?

**Comment by piddnad** [comment]
This is an interesting idea. We have tried SingleColorDecoder before, but the results were not as good as MultiScaleColorDecoder. Due to historical reasons, the weight files for the experiment have been lost. Currently, the ddcolor-paper-tiny model should be the smallest model. :)
