### ISSUE TITLE
about evaluation

### ISSUE THREAD

**Issue by menghuaa** [piddnad/DDColor#9]
When testing on the validation set of COCO Stuff, ADE20K, and ImageNet, did you first resize the input image to (512,512), and then linearly interpolate the coloring results to the original resolution?

**Comment by piddnad** [comment]
The answer is no. For validation, we follow the same approach as previous methods, i.e. for ImageNet val50k, COCO-Stuff, and ADE20K, the test images are **resized** into 256 x 256 (same as ColorFormer); for ImageNet val5k, the test images are **center cropped and resized** into 256 x 256 (same as CT2).

**Comment by menghuaa** [comment]
ImageNet val5k是ImageNet val50k验证集中的ILSVRC2012_val_00000001.JPEG~ILSVRC2012_val_00005000.JPEG吗? 我是用CT2中的`mini_size = min(w, h)
            img_transform = transforms.Compose([
                transforms.CenterCrop(mini_size),
                transforms.Resize(self.crop_size),
            ])`对ImageNet val5k进行center cropped和resized into 256 x 256，然后用您提供的ddcolor_paper.pth进行测试，但是结果和您论文中的不一致，cf的值我测出来是34.33，您论文中的值是38.26；fid我测出来3.78，论文中是3.92。计算指标是使用的CT2的eval_colorfullness.py和eval_fid.py.另外我发现CT2论文中
![image](https://github.com/piddnad/DDColor/assets/48876313/e200c627-037b-48a8-a055-5c2b134719d8)，△colorful是2.17，但是在您的论文中变成了0.27，这是怎么回事呢？

**Comment by piddnad** [comment]
Thank you for your interest in our research and for raising your concerns.

1. Yes, val5k means the first 5000 images in validation set.
2. For the △colorful, we calculated the average cf of ImageNet val5k to be 38.21. So we actually got better results with CT2 than what they reported in their paper.
3. The results described in our paper were obtained experimentally. However, we acknowledge that real-world results may vary due to various factors such as differences in machines and running environments. To better understand the differences, we encourage you to replicate our experiments in your own environment. 

While we appreciate the opportunity to discuss further, please understand that our time and resources are limited and we need to focus on our ongoing research. Thank you!

**Comment by menghuaa** [comment]
> Thank you for your interest in our research and for raising your concerns.
> 
> 1. Yes, val5k means the first 5000 images in validation set.
> 2. For the △colorful, we calculated the average cf of ImageNet val5k to be 38.21. So we actually got better results with CT2 than what they reported in their paper.
> 3. The results described in our paper were obtained experimentally. However, we acknowledge that real-world results may vary due to various factors such as differences in machines and running environments. To better understand the differences, we encourage you to replicate our experiments in your own environment.
> 
> While we appreciate the opportunity to discuss further, please understand that our time and resources are limited and we need to focus on our ongoing research. Thank you!
您论文中val5k和val50k的平均cf都是38.21，而且我算出来val5k没有resize之前的平均cf值才是38.21
